# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.15.11

mod_version = 1.21.1-1.0.0
maven_group=ru.feytox
archives_base_name=dontmineit

fabric_version=0.102.1+1.21.1

cloth_config_version = 15.0.130
modmenu_version = 11.0.0
